KLTN/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectKLTN.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectKLTN.Controllers
{
    public class AboutController : Controller
    {
        private readonly AppDbContext _appDbContext;
        public AboutController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }
        public IActionResult Index()
        {
            var abouts = _appDbContext.Abouts.ToList();

            return View(abouts);
     
        }
    }
}

KLTN/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProjectKLTN.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectKLTN.Controllers
{
    public class AdminController : Controller
    {
        private readonly AppDbContext _appDbContext;

        public AdminController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Support()
        {
            IEnumerable<Contact> contacts = _appDbContext.Contacts;

            return View(contacts);
        }
    }
}

     

KLTN/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectKLTN.Common;
using ProjectKLTN.Models;
using ProjectKLTN.ViewModels;

namespace ProjectKLTN.Controllers
{
    public class BlogController : Controller
    {
        private readonly AppDbContext _appDbContext;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BlogController(AppDbContext appDbContext, IWebHostEnvironment webHostEnvironment)
        {
            _appDbContext = appDbContext;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
         
            var products = _appDbContext.Blogs.Include(p => p.Category).ToList();

            return View(products);
        }

        public IActionResult Create()
        {
            BlogCreateVM productVM = new BlogCreateVM()
            {
                Blog = new Blog(),
                CategorySelectList = _appDbContext.Categories.Select(item => new SelectListItem
                {
                    Text = item.CategoryName,
                    Value = item.Id.ToString()
                }),
                TagSelectList = _appDbContext.Tags.Select(item => new SelectListItem
                {
                    Text = item.TagName,
                    Value = item.TagId.ToString()
                })
            };

            return View(productVM);
        }

        [HttpPost]
        public IActionResult Create(BlogCreateVM blogCreateVM)
        {
            
            var files = HttpContext.Request.Form.Files;
            string webRootPath = _webHostEnvironment.WebRootPath;

            string upload = webRootPath + CommonDefault.ImagePath;
            string fileName = Guid.NewGuid().ToString();
            string extension = Path.GetExtension(files[0].FileName);

            using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
            {
                files[0].CopyTo(fileStream);
            }

            blogCreateVM.Blog.Image = fileName + extension;

            
                foreach (var item in blogCreateVM.SelectListTagIds)
            {
                if (ModelState.IsValid)
                {
                    blogCreateVM.Blog.BlogTags.Add(new BlogTag()
                {
                    TagId = item
                });
            }

            _appDbContext.Blogs.Add(blogCreateVM.Blog);

            _appDbContext.SaveChanges();

            return RedirectToAction("Index");
            }
            return View(blogCreateVM);
        }



        public IActionResult Edit(int? id)
        {
            var product = _appDbContext.Blogs.Find(id);
            var tags = _appDbContext.Tags.ToList();
            var selectTags = product.BlogTags.Select(x => new Tag()
            {
                TagId = x.Tag.TagId,
                TagName = x.Tag.TagName
            });
            var selectList = new List<SelectListItem>();
            tags.ForEach(i => selectList.Add(new SelectListItem(i.TagName, i.TagId.ToString(), selectTags.Select(x => x.TagId).Contains(i.TagId))));
            BlogCreateVM productVM = new BlogCreateVM()
            {
                Blog = _appDbContext.Blogs.FirstOrDefault(item => item.Id == id),
                CategorySelectList = _appDbContext.Categories.Select(item => new SelectListItem
                {
                    Text = item.CategoryName,
                    Value = item.Id.ToString()
                }),
                TagSelectList = selectList
                /* SelectListTagIds = Product..Select(sc => sc.CourseId)*/
            };

            return View(productVM);
        }

        [HttpPost]
        public IActionResult Edit(BlogCreateVM blogCreateVM)
        {
            var files = HttpContext.Request.Form.Files;
            string webRootPath = _webHostEnvironment.WebRootPath;

            var objBlog = _appDbContext.Blogs.AsNoTracking().FirstOrDefault(pro => pro.Id == blogCreateVM.Blog.Id);

            if (files.Count > 0)
            {
                string upload = webRootPath + CommonDefault.ImagePath;
                string fileName = Guid.NewGuid().ToString();
                string extension = Path.GetExtension(files[0].FileName);

                using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                {
                    files[0].CopyTo(fileStream);
                }

                blogCreateVM.Blog.Image = fileName + extension;
            } else
            {
                blogCreateVM.Blog.Image = objBlog.Image;
            }

            _appDbContext.Blogs.Update(blogCreateVM.Blog);
            _appDbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var blog = _appDbContext.Blogs.Find(id);
            if (blog == null) return NotFound();

            return View(blog);
        }

        [HttpPost]
        public IActionResult DeleteBlog(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var blogs = _appDbContext.Blogs.Find(id);
            if (blogs == null) return NotFound();
            _appDbContext.Blogs.Remove(blogs);
            _appDbContext.SaveChanges();

            return RedirectToAction("Index");

        }

        
    }
}

KLTN/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectKLTN.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectKLTN.Controllers
{
    public class ContactController : Controller
    {
        private readonly AppDbContext _appDbContext;

        public ContactController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult CreateContact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateContact(Contact contact)
        {
            if (ModelState.IsValid)
            {
                _appDbContext.Contacts.Add(contact);
                _appDbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contact);
        }
    }
}

KLTN/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="~/img/favicon.png" type="image/png">
    <title>Technology BLog</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="~/vendors/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="~/vendors/animate-css/animate.css">
    <!-- main css -->
    <link rel="stylesheet" href="~/css/stylea.css">
    <link rel="stylesheet" href="~/css/responsive.css">
</head>
<body>
    <!--================Header Menu Area =================-->
    <header class="header_area">
        <div class="main_menu">
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <a class="navbar-brand logo_h" asp-controller="Home" asp-action="Index">Technology Blog</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                        <ul class="nav navbar-nav menu_nav ml-auto">
                            <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                            <li class="nav-item"><a class="nav-link" asp-controller="About" asp-action="Index">Giới thiệu</a></li>
                            <li class="nav-item"><a class="nav-link" asp-controller="Contact" asp-action="Index">Hỗ trợ</a></li>
                        </ul>
                    </div>
                    @*
                        <div class="right-button">
                           <ul>
                              <li><a class="sign_up" asp-controller="Admin" asp-action="Index">Admin</a></li>
                           </ul>
                        </div>
                    *@
                </div>
            </nav>
        </div>
    </header>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <footer class="footer-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-sm-6 mb-4 mb-xl-0 single-footer-widget">
                    <h4>Về chúng tôi</h4>
                    <p>Nơi cập nhật tin tức công nghệ mới nhất!</p>
                </div>
                <div class="col-lg-3 col-sm-6 mb-4 mb-xl-0 single-footer-widget">
                    <h4>Thông tin liên hệ</h4>
                    <div class="footer-address">
                        <p>
                            176 Trần Phú, Phước Vĩnh, TP. Huế
                        </p>
                        <span>
                            Phone :
                            0888888888
                        </span>
                        <span>
                            Email : phuxuanuniversity@gmail.com
                        </span>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6 mb-4 mb-xl-0 single-footer-widget">
                </div>
                <div class="col-lg-3 col-md-8 mb-4 mb-xl-0 single-footer-widget">
                    <h4>Newsletter</h4>
                    <p>Heaven fruitful doesn't over lesser in days. Appear creeping seasons deve behold bearing days open</p>
                    <div class="form-wrap" id="mc_embed_signup">
                        <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                              method="get">
                            <div class="input-group">
                                <input type="email" class="form-control" name="EMAIL" placeholder="Your Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your Email Address '">
                                <div class="input-group-append">
                                    <button class="btn click-btn" type="submit">
                                        <i class="fab fa-telegram-plane"></i>
                                    </button>
                                </div>
                            </div>
                            <div style="position: absolute; left: -5000px;">
                                <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                            </div>
                            <div class="info"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="footer-bottom row align-items-center text-center text-lg-left no-gutters">
                <p class="footer-text m-0 col-lg-8 col-md-12">
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> Technology Blog. All rights reserved.
                </p>
                <div class="col-lg-4 col-md-12 text-center text-lg-right footer-social">
                    <a href="#"><i class="ti-facebook"></i></a>
                    <a href="#"><i class="ti-twitter-alt"></i></a>
                    <a href="#"><i class="ti-dribbble"></i></a>
                    <a href="#"><i class="ti-linkedin"></i></a>
                </div>
            </div>
        </div>
    </footer>
    <!-- ================ End footer Area ================= -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="~/js/jquery-2.2.4.min.js"></script>
    <script src="~/js/popper.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/vendors/owl-carousel/owl.carousel.min.js"></script>
    <script src="~/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/js/waypoints.min.js"></script>
    <script src="~/js/mail-script.js"></script>
    <script src="~/js/contact.js"></script>
    <script src="~/js/jquery.form.js"></script>
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/mail-script.js"></script>
    <script src="~/js/theme.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

KLTN/Views/Shared/_LayoutDashBoard.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Basic Page Info -->
    <meta charset="utf-8">
    <title>DeskApp - Bootstrap Admin Dashboard HTML Template</title>
    <!-- Site favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="~/vendors/images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/vendors/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/vendors/images/favicon-16x16.png">
    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/core.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/icon-font.min.css">
    <link rel="stylesheet" type="text/css" href="~/src/plugins/datatables/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="~/src/plugins/datatables/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/styles/styled.css">
    <link rel="stylesheet" href="~/font-awesome/css/all.css" />
    
</head>
<body>
    <div class="header">
        <div class="header-left">
            <div class="menu-icon dw dw-menu"></div>
            <span>&nbsp;&nbsp;&nbsp;</span>
            @*   <a class="btn btn-danger" asp-controller="Home" asp-action="Index">Quay về Website</a>*@
        </div>
        <span>
            <partial name="_LoginPartial.cshtml" />
        </span>
        </a>
        @*
            <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">*@
        @*<a class="dropdown-item" href="profile.html"><i class="dw dw-user1"></i> Profile</a>
            <a class="dropdown-item" href="login.html"><i class="dw dw-logout"></i> Log Out</a>*@
        @*
            </div>
        *@
    </div>
    <div class="left-side-bar">
        <div class="brand-logo">
            <a asp-controller="Admin" asp-action="Index">
                @* <img src="~/vendors/images/deskapp-logo.svg" alt="" class="dark-logo">
                    <img src="~/vendors/images/deskapp-logo-white.svg" alt="" class="light-logo">*@
            </a>
            <div class="close-sidebar" data-toggle="left-sidebar-close">
                <i class="ion-close-round"></i>
            </div>
        </div>
        <div class="menu-block customscroll">
            <div class="sidebar-menu">
                <ul id="accordion-menu">
                    <li>
                        <a asp-controller="Admin" asp-action="Index" class="dropdown-toggle no-arrow">
                            <span class="micon dw dw-house-1"></span><span class="mtext">Home</span>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Category" asp-action="Index" class="dropdown-toggle no-arrow">
                            <span class="micon dw dw-list3"></span><span class="mtext">Quản lý thể loại</span>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Blog" asp-action="Index" class="dropdown-toggle no-arrow">
                            <span class="micon dw dw-newspaper"></span><span class="mtext">Quản lý bài viết</span>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Admin" asp-action="Support" class="dropdown-toggle no-arrow">
                            <span class="micon dw dw-support"></span><span class="mtext">Quản lý hỗ trợ</span>
                        </a>
                    </li>
                    @*
                        <li>
                           <a asp-controller="Admin" asp-action="Blog" class="dropdown-toggle no-arrow">
                           <span class="micon dw dw-support"></span><span class="mtext">Support</span>
                           </a>
                        </li>
                    *@
                </ul>
            </div>
        </div>
    </div>
    <div class="mobile-menu-overlay"></div>
    <div>
        <div class="main-container">
            <main role="main">
                @RenderBody()
            </main>
        </div>
    </div>
    <!-- js -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <script src="~/vendors/scripts/core.js"></script>
    <script src="~/vendors/scripts/script.min.js"></script>
    <script src="~/vendors/scripts/process.js"></script>
    <script src="~/vendors/scripts/layout-settings.js"></script>
    <script src="~/src/plugins/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/src/plugins/datatables/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/src/plugins/datatables/js/dataTables.responsive.min.js"></script>
    <script src="~/src/plugins/datatables/js/responsive.bootstrap4.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

KLTN/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Basic Page Info -->
    <meta charset="utf-8">
    <title>Admin Page</title>
    <!-- Site favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="~/adminJS/vendors/images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/adminJS/vendors/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/adminJS/vendors/images/favicon-16x16.png">
    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="~/adminJS/vendors/styles/core.css">
    <link rel="stylesheet" type="text/css" href="~/adminJS/vendors/styles/icon-font.min.css">
    <link rel="stylesheet" type="text/css" href="~/adminJS/vendors/styles/style.css">
</head>
<body class="login-page">
    @RenderBody()
    <script src="~/adminJS/vendors/scripts/core.js"></script>
    <script src="~/adminJS/vendors/scripts/script.min.js"></script>
    <script src="~/adminJS/vendors/scripts/process.js"></script>
    <script src="~/adminJS/vendors/scripts/layout-settings.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>